config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

name: 'unified_rag'
version: '0.1.0'

vars:
  unified_rag:
    ## Zendesk Sources
    zendesk_ticket: "{{ source('rag_zendesk', 'ticket') }}"
    zendesk_ticket_comment: "{{ source('rag_zendesk', 'ticket_comment') }}"
    zendesk_user: "{{ source('rag_zendesk', 'user') }}"

    ## Jira Sources
    jira_issue: "{{ source('rag_jira', 'issue') }}"
    jira_comment: "{{ source('rag_jira', 'comment') }}"
    jira_user: "{{ source('rag_jira', 'user') }}"
    jira_status: "{{ source('rag_jira', 'status') }}"
    jira_priority: "{{ source('rag_jira', 'priority') }}"

models:
  unified_rag:
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: view